<style>
    table.minimalistBlack {
  border: 1px solid #000000;
  width: 100%;
  text-align: left;
  border-collapse: collapse;
}
table.minimalistBlack td, table.minimalistBlack th {
  border: 1px solid #000000;
  padding: 5px 4px;
}
table.minimalistBlack tbody td {
  font-size: 13px;
}
table.minimalistBlack tfoot td {
  font-size: 14px;
}
</style>

<table class="minimalistBlack">
<tbody>
<tr>
<td><strong><span lang="UZ" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">Oʻquv yili</span><span lang="RU" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: RU; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;"> (</span><span lang="UZ" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">semestri</span><span lang="RU" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: RU; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">)</span></strong></td>
<td><strong><span lang="UZ" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">Taʻlim olish joyi va oʻqitishning toʻlov miqdori tegishli boʻlgan oliy taʻlim tashkiloti</span></strong></td>
<td><strong><span lang="UZ" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">Oʻqitishning toʻlov miqdori</span></strong></td>
<td><strong><span lang="UZ" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">Toʻlovlar reja-jadvali</span></strong></td>
</tr>
<tr>
<td><span lang="UZ" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">2022/2023- oʻquv yili</span></td>
<td>
<p class="MsoNormal" style="text-align: center; mso-line-height-alt: 1.0pt;" align="center"><span lang="UZ" style="font-size: 9.0pt; mso-ansi-language: UZ; mso-no-proof: yes;">KAZGYU</span><span lang="UZ" style="background-color: transparent; text-align: left; font-size: 9pt; font-family: 'Times New Roman', 'serif';">(mazkur oʻquv yilida </span><span style="background-color: transparent; text-align: left; font-size: 9pt; font-family: 'Times New Roman', 'serif';">oʻqitishning toʻlov miqdor</span><span lang="UZ" style="background-color: transparent; text-align: left; font-size: 9pt; font-family: 'Times New Roman', 'serif';">ining 100%)</span></p>
</td>
<td><span lang="UZ" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">32&nbsp;999&nbsp;340<br /> </span><span lang="UZ-CYR" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ-CYR; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">(</span><span lang="UZ" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">oʻttiz ikki million toʻqqiz yuz toʻqson toʻqiz ming uch yuz qirq</span><span lang="UZ-CYR" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ-CYR; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">)</span><span lang="UZ" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;"> soʻm</span></td>
<td>
<p class="MsoNormal" style="text-align: justify;"><span lang="UZ-CYR" style="font-size: 9.0pt; mso-ansi-language: UZ-CYR; mso-no-proof: yes;">01.11.2022 </span><span lang="UZ" style="font-size: 9.0pt; mso-ansi-language: UZ; mso-no-proof: yes;">ga qadar &ndash; </span><span lang="UZ-CYR" style="font-size: 9.0pt; mso-ansi-language: UZ-CYR; mso-no-proof: yes;">16&nbsp;499&nbsp;670 </span><span lang="UZ" style="font-size: 9.0pt; mso-ansi-language: UZ; mso-no-proof: yes;">(</span><span lang="UZ-CYR" style="font-size: 9.0pt; mso-ansi-language: UZ-CYR; mso-no-proof: yes;">oʻn olti million toʻrt yuz toʻqson toʻqqiz ming olti yuz yetmish</span><span lang="UZ" style="font-size: 9.0pt; mso-ansi-language: UZ; mso-no-proof: yes;">)</span> <span lang="UZ" style="font-size: 9.0pt; mso-ansi-language: UZ; mso-no-proof: yes;">soʻm;</span></p>
<span lang="UZ-CYR" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ-CYR; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">01.02.2023 </span><span lang="UZ" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">ga qadar &ndash; </span><span lang="UZ-CYR" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ-CYR; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">16&nbsp;499&nbsp;670 </span><span lang="UZ" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">(</span><span lang="UZ-CYR" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ-CYR; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">oʻn olti million toʻrt yuz toʻqson toʻqqiz ming olti yuz yetmish</span><span lang="UZ" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">)</span> <span lang="UZ" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">soʻm</span><span lang="UZ-CYR" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ-CYR; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">.</span></td>
</tr>
<tr>
<td><span lang="UZ" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">2023/2024- oʻquv yili</span></td>
<td>
<p class="MsoNormal" style="text-align: center; mso-line-height-alt: 1.0pt;" align="center"><span lang="UZ" style="font-size: 9.0pt; mso-ansi-language: UZ; mso-no-proof: yes;">KAZGYU</span><span lang="UZ" style="background-color: transparent; text-align: left; font-size: 9pt; font-family: 'Times New Roman', 'serif';">(mazkur oʻquv yilida </span><span style="background-color: transparent; text-align: left; font-size: 9pt; font-family: 'Times New Roman', 'serif';">oʻqitishning toʻlov miqdor</span><span lang="UZ" style="background-color: transparent; text-align: left; font-size: 9pt; font-family: 'Times New Roman', 'serif';">ining 100%)</span></p>
</td>
<td><span lang="UZ" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">32&nbsp;999&nbsp;340<br /> </span><span lang="UZ-CYR" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ-CYR; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">(</span><span lang="UZ" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">oʻttiz ikki million toʻqqiz yuz toʻqson toʻqiz ming uch yuz qirq</span><span lang="UZ-CYR" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ-CYR; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">)</span><span lang="UZ" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;"> soʻm</span></td>
<td>
<p class="MsoNormal" style="text-align: justify;"><span lang="UZ-CYR" style="font-size: 9.0pt; mso-ansi-language: UZ-CYR; mso-no-proof: yes;">01.09.2023 </span><span lang="UZ" style="font-size: 9.0pt; mso-ansi-language: UZ; mso-no-proof: yes;">ga qadar &ndash; </span><span lang="UZ-CYR" style="font-size: 9.0pt; mso-ansi-language: UZ-CYR; mso-no-proof: yes;">16&nbsp;499&nbsp;670 </span><span lang="UZ" style="font-size: 9.0pt; mso-ansi-language: UZ; mso-no-proof: yes;">(</span><span lang="UZ-CYR" style="font-size: 9.0pt; mso-ansi-language: UZ-CYR; mso-no-proof: yes;">oʻn olti million toʻrt yuz toʻqson toʻqqiz ming olti yuz yetmish</span><span lang="UZ" style="font-size: 9.0pt; mso-ansi-language: UZ; mso-no-proof: yes;">)</span> <span lang="UZ" style="font-size: 9.0pt; mso-ansi-language: UZ; mso-no-proof: yes;">soʻm;</span></p>
<span lang="UZ-CYR" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ-CYR; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">01.02.2024 </span><span lang="UZ" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">ga qadar &ndash; </span><span lang="UZ-CYR" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ-CYR; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">16&nbsp;499&nbsp;670 </span><span lang="UZ" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">(</span><span lang="UZ-CYR" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ-CYR; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">oʻn olti million toʻrt yuz toʻqson toʻqqiz ming olti yuz yetmish</span><span lang="UZ" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">)</span> <span lang="UZ" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">soʻm</span><span lang="UZ-CYR" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ-CYR; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">.</span></td>
</tr>
<tr>
<td>
<p class="MsoNormal" style="text-align: center; mso-line-height-alt: 1.0pt;" align="center"><span lang="UZ-CYR" style="font-size: 9.0pt; mso-ansi-language: UZ-CYR; mso-no-proof: yes;">2024/2025</span></p>
<span lang="UZ" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">oʻquv yili</span><span lang="UZ-CYR" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ-CYR; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">-</span></td>
<td>
<p class="MsoNormal" style="text-align: center; mso-line-height-alt: 1.0pt;" align="center"><span lang="UZ" style="font-size: 9.0pt; mso-ansi-language: UZ; mso-no-proof: yes;">TDYU</span><span lang="UZ" style="background-color: transparent; text-align: left; font-size: 9pt; font-family: 'Times New Roman', 'serif';">(mazkur oʻquv yilida </span><span style="background-color: transparent; text-align: left; font-size: 9pt; font-family: 'Times New Roman', 'serif';">oʻqitishning toʻlov miqdor</span><span lang="UZ" style="background-color: transparent; text-align: left; font-size: 9pt; font-family: 'Times New Roman', 'serif';">ining 100%)</span></p>
</td>
<td><span lang="UZ" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">34</span><span style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: EN-US; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">&nbsp;</span><span lang="UZ" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">500</span><span style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: EN-US; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">&nbsp;</span><span lang="UZ" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">000<br /> </span><span lang="UZ-CYR" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ-CYR; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">(</span><span lang="UZ" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">oʻttiz toʻrt million besh yuz ming) soʻm*</span></td>
<td>
<p class="MsoNormal" style="text-align: justify; mso-line-height-alt: 1.0pt;"><span style="font-size: 9.0pt; mso-ansi-language: EN-US; mso-no-proof: yes;">15.10.202</span><span lang="UZ-CYR" style="font-size: 9.0pt; mso-ansi-language: UZ-CYR; mso-no-proof: yes;">4</span> <span lang="UZ" style="font-size: 9.0pt; mso-ansi-language: UZ; mso-no-proof: yes;">ga qadar &ndash; </span><span style="font-size: 9.0pt; mso-ansi-language: EN-US; mso-no-proof: yes;">8&nbsp;625&nbsp;000 (sakkiz million olti yuz yigirma besh ming) soʻm;</span></p>
<p class="MsoNormal" style="text-align: justify; mso-line-height-alt: 1.0pt;"><span style="font-size: 9.0pt; mso-ansi-language: EN-US; mso-no-proof: yes;">15.12.202</span><span lang="UZ-CYR" style="font-size: 9.0pt; mso-ansi-language: UZ-CYR; mso-no-proof: yes;">4</span> <span lang="UZ" style="font-size: 9.0pt; mso-ansi-language: UZ; mso-no-proof: yes;">ga qadar &ndash; </span><span style="font-size: 9.0pt; mso-ansi-language: EN-US; mso-no-proof: yes;">8&nbsp;625&nbsp;000 (sakkiz million olti yuz yigirma besh ming) soʻm;</span></p>
<p class="MsoNormal" style="text-align: justify; mso-line-height-alt: 1.0pt;"><span style="font-size: 9.0pt; mso-ansi-language: EN-US; mso-no-proof: yes;">15.02.202</span><span lang="UZ-CYR" style="font-size: 9.0pt; mso-ansi-language: UZ-CYR; mso-no-proof: yes;">5</span> <span lang="UZ" style="font-size: 9.0pt; mso-ansi-language: UZ; mso-no-proof: yes;">ga qadar &ndash; </span><span style="font-size: 9.0pt; mso-ansi-language: EN-US; mso-no-proof: yes;">8&nbsp;625&nbsp;000 (sakkiz million olti yuz yigirma besh ming) soʻm;</span></p>
<span style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: EN-US; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">01.05.202</span><span lang="UZ-CYR" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ-CYR; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">5</span> <span lang="UZ" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">ga qadar &ndash; </span><span style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: EN-US; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">8&nbsp;625&nbsp;000 (sakkiz million olti yuz yigirma besh ming) soʻm.</span></td>
</tr>
<tr>
<td><span lang="UZ" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">202</span><span lang="UZ-CYR" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ-CYR; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">5</span><span lang="UZ" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">/202</span><span lang="UZ-CYR" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ-CYR; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">6</span><span lang="UZ" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">- oʻquv yili<br /> kuzgi semestri</span></td>
<td>
<p class="MsoNormal" style="text-align: center; mso-line-height-alt: 1.0pt;" align="center"><span lang="UZ" style="font-size: 9.0pt; mso-ansi-language: UZ; mso-no-proof: yes;">KAZGYU</span><span lang="UZ" style="background-color: transparent; text-align: left; font-size: 9pt; font-family: 'Times New Roman', 'serif';">(mazkur semestrda </span><span style="background-color: transparent; text-align: left; font-size: 9pt; font-family: 'Times New Roman', 'serif';">oʻqitishning toʻlov miqdor</span><span lang="UZ" style="background-color: transparent; text-align: left; font-size: 9pt; font-family: 'Times New Roman', 'serif';">ining 100%)</span></p>
</td>
<td><span lang="UZ" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">10&nbsp;999&nbsp;780 (oʻn million toʻqqiz yuz toʻqson toʻqqiz ming yetti yuz sakson) soʻm</span></td>
<td><span lang="UZ-CYR" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ-CYR; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">01.09.2025 </span><span lang="UZ" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">ga qadar &ndash; 10&nbsp;999&nbsp;780 (oʻn million toʻqqiz yuz toʻqson toʻqqiz ming yetti yuz sakson) soʻm</span><span lang="UZ-CYR" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ-CYR; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">.</span></td>
</tr>
<tr>
<td><span lang="UZ" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">202</span><span lang="UZ-CYR" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ-CYR; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">5</span><span lang="UZ" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">/202</span><span lang="UZ-CYR" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ-CYR; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">6</span><span lang="UZ" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">- oʻquv yili<br /> bahorgi semestri</span></td>
<td>
<p class="MsoNormal" style="text-align: center; mso-line-height-alt: 1.0pt;" align="center"><span lang="UZ" style="font-size: 9.0pt; mso-ansi-language: UZ; mso-no-proof: yes;">KAZGYU</span><span lang="UZ" style="background-color: transparent; text-align: left; font-size: 9pt; font-family: 'Times New Roman', 'serif';">(mazkur oʻquv yilida </span><span style="background-color: transparent; text-align: left; font-size: 9pt; font-family: 'Times New Roman', 'serif';">oʻqitishning toʻlov miqdor</span><span lang="UZ" style="background-color: transparent; text-align: left; font-size: 9pt; font-family: 'Times New Roman', 'serif';">ining 100%)</span></p>
</td>
<td><span lang="UZ" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">23&nbsp;100&nbsp;000<br /> </span><span lang="UZ-CYR" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ-CYR; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">(</span><span lang="UZ" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">yigirma uch million yuz ming</span><span lang="UZ-CYR" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ-CYR; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">)</span><span lang="UZ" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;"> soʻm**</span></td>
<td>
<p class="MsoNormal" style="text-align: justify; mso-line-height-alt: 1.0pt;"><span style="font-size: 9.0pt; mso-ansi-language: EN-US; mso-no-proof: yes;">15.02.2026 </span><span lang="UZ" style="font-size: 9.0pt; mso-ansi-language: UZ; mso-no-proof: yes;">ga qadar &ndash; </span><span style="font-size: 9.0pt; mso-ansi-language: EN-US; mso-no-proof: yes;">5&nbsp;775&nbsp;000 (bech million yetti yuz yetmish besh ming) soʻm;</span></p>
<span style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: EN-US; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">01.05.2026 </span><span lang="UZ" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">ga qadar &ndash; </span><span style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: EN-US; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">5&nbsp;775&nbsp;000 (bech million yetti yuz yetmish besh ming) soʻm.</span></td>
</tr>
</tbody>
</table>
