<style>
    table.blueTable {
  border: 1px solid #000000;
  background-color: #FFFFFF;
  width: 100%;
  text-align: left;
  border-collapse: collapse;
}
table.blueTable td, table.blueTable th {
  border: 1px solid #000000;
  padding: 3px 2px;
}
table.blueTable tbody td {
  font-size: 11px;
}
table.blueTable tfoot td {
  font-size: 11px;
}
table.blueTable tfoot .links {
  text-align: right;
}
table.blueTable tfoot .links a{
  display: inline-block;
  background: #1C6EA4;
  color: #FFFFFF;
  padding: 2px 8px;
  border-radius: 5px;
}
</style>
<table class="blueTable">
<tbody>
<tr>
<td>&nbsp;<strong><span lang="UZ" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">Oʻquv yili</span></strong></td>
<td>&nbsp;<strong><span lang="UZ" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">Taʻlim olish joyi va oʻqitishning toʻlov miqdori tegishli boʻlgan oliy taʻlim tashkiloti</span></strong></td>
<td>&nbsp;<strong><span lang="UZ" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">Oʻqitishning toʻlov miqdori</span></strong></td>
<td><strong><span lang="UZ" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">Toʻlovlar reja-jadvali</span></strong>&nbsp;</td>
</tr>
<tr>
<td>&nbsp;2022/2023- oʻquv yili</td>
<td>&nbsp;UrDYU<br /> <span lang="UZ" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">(mazkur oʻquv yilida </span><span style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: EN-US; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">oʻqitishning toʻlov miqdor</span><span lang="UZ" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">ining 100%)</span></td>
<td>&nbsp;36&nbsp;400<span lang="UZ-CYR" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ-CYR; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">&nbsp;000<br /> (</span><span lang="UZ" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">oʻttiz olti million toʻrt yuz ming</span><span lang="UZ-CYR" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ-CYR; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">)</span><span style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: EN-US; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;"> soʻm</span></td>
<td>&nbsp;20.09.2022 ga qadar &ndash; 4&nbsp;550&nbsp;000 (toʻrt million besh yuz ellik ming) soʻm<span style="text-align: justify; font-size: 9pt;">;</span>
<p class="MsoNormal" style="text-align: justify; mso-line-height-alt: 1.0pt;"><span lang="UZ" style="font-size: 9.0pt; mso-ansi-language: UZ; mso-no-proof: yes;">25.10.2022 ga qadar &ndash; 4&nbsp;550&nbsp;000 (toʻrt million besh yuz ellik ming) soʻm</span><span style="font-size: 9.0pt; mso-ansi-language: EN-US; mso-no-proof: yes;">;</span></p>
<p class="MsoNormal" style="text-align: justify; mso-line-height-alt: 1.0pt;"><span lang="UZ" style="font-size: 9.0pt; mso-ansi-language: UZ; mso-no-proof: yes;">25.11.2022 ga qadar &ndash; 4&nbsp;550&nbsp;000 (toʻrt million besh yuz ellik ming) soʻm</span><span style="font-size: 9.0pt; mso-ansi-language: EN-US; mso-no-proof: yes;">;</span></p>
<p class="MsoNormal" style="text-align: justify; mso-line-height-alt: 1.0pt;"><span lang="UZ" style="font-size: 9.0pt; mso-ansi-language: UZ; mso-no-proof: yes;">25.12.2022 ga qadar &ndash; 4&nbsp;550&nbsp;000 (toʻrt million besh yuz ellik ming) soʻm</span><span style="font-size: 9.0pt; mso-ansi-language: EN-US; mso-no-proof: yes;">;</span></p>
<p class="MsoNormal" style="text-align: justify; mso-line-height-alt: 1.0pt;"><span lang="UZ" style="font-size: 9.0pt; mso-ansi-language: UZ; mso-no-proof: yes;">25.02.2023 ga qadar &ndash; 4&nbsp;550&nbsp;000 (toʻrt million besh yuz ellik ming) soʻm</span><span style="font-size: 9.0pt; mso-ansi-language: EN-US; mso-no-proof: yes;">;</span></p>
<p class="MsoNormal" style="text-align: justify; mso-line-height-alt: 1.0pt;"><span lang="UZ" style="font-size: 9.0pt; mso-ansi-language: UZ; mso-no-proof: yes;">25.03.2023 ga qadar &ndash; 4&nbsp;550&nbsp;000 (toʻrt million besh yuz ellik ming) soʻm</span><span style="font-size: 9.0pt; mso-ansi-language: EN-US; mso-no-proof: yes;">;</span></p>
<p class="MsoNormal" style="text-align: justify; mso-line-height-alt: 1.0pt;"><span lang="UZ" style="font-size: 9.0pt; mso-ansi-language: UZ; mso-no-proof: yes;">25.04.2023 ga qadar &ndash; 4&nbsp;550&nbsp;000 (toʻrt million besh yuz ellik ming) soʻm</span><span style="font-size: 9.0pt; mso-ansi-language: EN-US; mso-no-proof: yes;">;</span></p>
<span lang="UZ" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">25.05.2023 ga qadar &ndash; 4&nbsp;550&nbsp;000 (toʻrt million besh yuz ellik ming) soʻm</span><span style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: EN-US; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">.</span></td>
</tr>
<tr>
<td>&nbsp;2023/2024- oʻquv yili</td>
<td>&nbsp;TDYU<br /> <span lang="UZ" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">(mazkur oʻquv yilida </span><span style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: EN-US; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">oʻqitishning toʻlov miqdor</span><span lang="UZ" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">ining 100%)</span></td>
<td>&nbsp;39&nbsp;000&nbsp;000<br /> <span lang="UZ-CYR" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ-CYR; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">(</span><span lang="UZ" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">oʻttiz toʻqqiz<br /> millon) soʻm*</span></td>
<td>&nbsp;15.10.2023 <span lang="UZ" style="text-align: justify; font-size: 9pt;">ga qadar &ndash; </span><span style="text-align: justify; font-size: 9pt;">9&nbsp;750&nbsp;000 (toʻqqiz million yeti yuz ellik ming) soʻm;</span>
<p class="MsoNormal" style="text-align: justify; mso-line-height-alt: 1.0pt;"><span style="font-size: 9.0pt; mso-ansi-language: EN-US; mso-no-proof: yes;">15.12.2023 </span><span lang="UZ" style="font-size: 9.0pt; mso-ansi-language: UZ; mso-no-proof: yes;">ga qadar &ndash; </span><span style="font-size: 9.0pt; mso-ansi-language: EN-US; mso-no-proof: yes;">9&nbsp;750&nbsp;000 (toʻqqiz million yeti yuz ellik ming) soʻm;</span></p>
<p class="MsoNormal" style="text-align: justify; mso-line-height-alt: 1.0pt;"><span style="font-size: 9.0pt; mso-ansi-language: EN-US; mso-no-proof: yes;">15.02.2024 </span><span lang="UZ" style="font-size: 9.0pt; mso-ansi-language: UZ; mso-no-proof: yes;">ga qadar &ndash; </span><span style="font-size: 9.0pt; mso-ansi-language: EN-US; mso-no-proof: yes;">9&nbsp;750&nbsp;000 (toʻqqiz million yeti yuz ellik ming) soʻm;</span></p>
<span style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: EN-US; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">01.05.2024 </span><span lang="UZ" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">ga qadar &ndash; </span><span style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: EN-US; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">9&nbsp;750&nbsp;000 (toʻqqiz million yeti yuz ellik ming) soʻm.</span></td>
</tr>
<tr>
<td>&nbsp;2024/2025- oʻquv yili</td>
<td>&nbsp;UrDYU<br /> <span lang="UZ" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">(mazkur oʻquv yilida </span><span style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: EN-US; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">oʻqitishning toʻlov miqdor</span><span lang="UZ" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">ining 100%)</span></td>
<td>&nbsp;36&nbsp;400<span lang="UZ-CYR" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ-CYR; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">&nbsp;000<br /> (</span><span lang="UZ" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">oʻttiz olti million toʻrt yuz ming</span><span lang="UZ-CYR" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ-CYR; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">)</span><span lang="UZ" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;"> soʻm</span></td>
<td>&nbsp;25.09.202<span lang="UZ-CYR" style="text-align: justify; font-size: 9pt;">4</span><span lang="UZ" style="text-align: justify; font-size: 9pt;"> ga qadar &ndash; 4&nbsp;550&nbsp;000 (toʻrt million besh yuz ellik ming) soʻm</span><span style="text-align: justify; font-size: 9pt;">;</span>
<p class="MsoNormal" style="text-align: justify; mso-line-height-alt: 1.0pt;"><span lang="UZ" style="font-size: 9.0pt; mso-ansi-language: UZ; mso-no-proof: yes;">25.10.202</span><span lang="UZ-CYR" style="font-size: 9.0pt; mso-ansi-language: UZ-CYR; mso-no-proof: yes;">4</span><span lang="UZ" style="font-size: 9.0pt; mso-ansi-language: UZ; mso-no-proof: yes;"> ga qadar &ndash; 4&nbsp;550&nbsp;000 (toʻrt million besh yuz ellik ming) soʻm</span><span style="font-size: 9.0pt; mso-ansi-language: EN-US; mso-no-proof: yes;">;</span></p>
<p class="MsoNormal" style="text-align: justify; mso-line-height-alt: 1.0pt;"><span lang="UZ" style="font-size: 9.0pt; mso-ansi-language: UZ; mso-no-proof: yes;">25.11.202</span><span lang="UZ-CYR" style="font-size: 9.0pt; mso-ansi-language: UZ-CYR; mso-no-proof: yes;">4</span><span lang="UZ" style="font-size: 9.0pt; mso-ansi-language: UZ; mso-no-proof: yes;"> ga qadar &ndash; 4&nbsp;550&nbsp;000 (toʻrt million besh yuz ellik ming) soʻm</span><span style="font-size: 9.0pt; mso-ansi-language: EN-US; mso-no-proof: yes;">;</span></p>
<p class="MsoNormal" style="text-align: justify; mso-line-height-alt: 1.0pt;"><span lang="UZ" style="font-size: 9.0pt; mso-ansi-language: UZ; mso-no-proof: yes;">25.12.202</span><span lang="UZ-CYR" style="font-size: 9.0pt; mso-ansi-language: UZ-CYR; mso-no-proof: yes;">4</span><span lang="UZ" style="font-size: 9.0pt; mso-ansi-language: UZ; mso-no-proof: yes;"> ga qadar &ndash; 4&nbsp;550&nbsp;000 (toʻrt million besh yuz ellik ming) soʻm</span><span style="font-size: 9.0pt; mso-ansi-language: EN-US; mso-no-proof: yes;">;</span></p>
<p class="MsoNormal" style="text-align: justify; mso-line-height-alt: 1.0pt;"><span lang="UZ" style="font-size: 9.0pt; mso-ansi-language: UZ; mso-no-proof: yes;">25.02.202</span><span lang="UZ-CYR" style="font-size: 9.0pt; mso-ansi-language: UZ-CYR; mso-no-proof: yes;">5</span><span lang="UZ" style="font-size: 9.0pt; mso-ansi-language: UZ; mso-no-proof: yes;"> ga qadar &ndash; 4&nbsp;550&nbsp;000 (toʻrt million besh yuz ellik ming) soʻm</span><span style="font-size: 9.0pt; mso-ansi-language: EN-US; mso-no-proof: yes;">;</span></p>
<p class="MsoNormal" style="text-align: justify; mso-line-height-alt: 1.0pt;"><span lang="UZ" style="font-size: 9.0pt; mso-ansi-language: UZ; mso-no-proof: yes;">25.03.202</span><span lang="UZ-CYR" style="font-size: 9.0pt; mso-ansi-language: UZ-CYR; mso-no-proof: yes;">5</span><span lang="UZ" style="font-size: 9.0pt; mso-ansi-language: UZ; mso-no-proof: yes;"> ga qadar &ndash; 4&nbsp;550&nbsp;000 (toʻrt million besh yuz ellik ming) soʻm</span><span style="font-size: 9.0pt; mso-ansi-language: EN-US; mso-no-proof: yes;">;</span></p>
<p class="MsoNormal" style="text-align: justify; mso-line-height-alt: 1.0pt;"><span lang="UZ" style="font-size: 9.0pt; mso-ansi-language: UZ; mso-no-proof: yes;">25.04.202</span><span lang="UZ-CYR" style="font-size: 9.0pt; mso-ansi-language: UZ-CYR; mso-no-proof: yes;">5</span><span lang="UZ" style="font-size: 9.0pt; mso-ansi-language: UZ; mso-no-proof: yes;"> ga qadar &ndash; 4&nbsp;550&nbsp;000 (toʻrt million besh yuz ellik ming) soʻm</span><span style="font-size: 9.0pt; mso-ansi-language: EN-US; mso-no-proof: yes;">;</span></p>
<span lang="UZ" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">25.05.202</span><span lang="UZ-CYR" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ-CYR; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">5</span><span lang="UZ" style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: UZ; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;"> ga qadar &ndash; 4&nbsp;550&nbsp;000 (toʻrt million besh yuz ellik ming) soʻm</span><span style="font-size: 9.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: EN-US; mso-fareast-language: RU; mso-bidi-language: AR-SA; mso-no-proof: yes;">.</span></td>
</tr>
</tbody>
</table>
